# Generated by Django 4.2.7 on 2024-01-19 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_assignements_alter_subject_no_of_classes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignements',
            name='grades',
        ),
    ]
