# Generated by Django 4.2.7 on 2024-01-21 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_assignements_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignements',
            name='submitted_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.staff_data'),
        ),
    ]
