# Generated by Django 4.2.7 on 2024-01-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_assignements_submitted_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignements',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
