# Generated by Django 4.2.7 on 2023-11-11 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0003_alter_count_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='count',
            old_name='name',
            new_name='name_2',
        ),
    ]
