# Generated by Django 4.2.7 on 2023-11-11 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0004_rename_name_count_name_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='count',
            old_name='name_2',
            new_name='name',
        ),
    ]
