# Generated by Django 4.2.7 on 2023-11-12 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_attendance_student_alter_student_name'),
        ('user_accounts', '0005_rename_name_2_count_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
    ]
